// The DCE/RPC session table (dcerpc_session.h) on its own: presentation contexts, calls, fragment chains, the endpoint mapper's
// answers and the port map. Oracle for the endpoint mapper bytes: scratchpad g12c/dce.py, an independent Python `struct` encoder of
// C706 appendix L towers (floors: interface UUID + major / minor version, transfer syntax, RPC protocol, TCP / UDP port big-endian,
// IP address, named pipe) and of the NDR layout of the answers of ept_map (opnum 3: handle, num_towers, conformant varying array of
// pointers, deferred towers) and ept_lookup (opnum 2: entries with object UUID, tower pointer and a varying annotation string).
#include <gtest/gtest.h>

#include <random>

#include <dissect/dcerpc_session.h>

#include "support.h"

using dissect::DceNote;
using dissect::DcePdu;
using dissect::DceRpcTable;

namespace {
    std::string raw(const std::string &hexText) {
        const auto v = support::hex(hexText);
        return std::string(v.begin(), v.end());
    }

    // generated by dce.py
    const char *kTowerTcp = "050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b020000000100070200c20301000904000a000002";
    const char *kTowerNp = "050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b0200000001000f0d005c504950455c73727673766300010011010000";
    const char *kMapOne = "000000000000000000000000000000000000000001000000040000000000000001000000000002004b0000004b000000050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b020000000100070200c20301000904000a0000020000000000";
    const char *kMapBe = "000000000000000000000000000000000000000000000001000000040000000000000001000200000000004b0000004b050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b020000000100070200c20301000904000a0000020000000000";
    const char *kMapTwo = "00000000000000000000000000000000000000000200000004000000000000000200000000000200040002004b0000004b000000050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b020000000100070200c20301000904000a000002005300000053000000050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b0200000001000f0d005c504950455c737276737663000100110100000000000000";
    const char *kLookup = "0000000000000000000000000000000000000000030000000800000000000000030000000000000000000000000000000000000000000200000000000700000053657276657200000000000000000000000000000000000004000200000000000400000053414d0000000000000000000000000000000000080002000000000001000000000000004b0000004b000000050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b020000000100070200c20301000904000a000002004b0000004b000000050013000d785734123412cdabef000123456789ac01000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000b020000000100070200c20301000904000a000002004b0000004b000000050013000dc84f324b7016d30112785a47bf6ee18803000200000013000d045d888aeb1cc9119fe808002b10486002000200000001000a020000000100080200c22401000904000a0000020000000000";

    const char *kSrvsvc = "4b324fc8-1670-01d3-1278-5a47bf6ee188";
    const char *kSamr = "12345778-1234-abcd-ef00-0123456789ac";

    DcePdu bind(uint32_t call, std::vector<dissect::DceContext> contexts) {
        DcePdu p;
        p.type = dissect::kDceBind;
        p.callId = call;
        p.contexts = std::move(contexts);
        return p;
    }
    DcePdu bindAck(uint32_t call, std::vector<uint16_t> results) {
        DcePdu p;
        p.type = dissect::kDceBindAck;
        p.callId = call;
        p.results = std::move(results);
        return p;
    }
    DcePdu request(uint32_t call, uint16_t ctx, uint16_t opnum, bool first = true, bool last = true) {
        DcePdu p;
        p.type = dissect::kDceRequest;
        p.callId = call;
        p.contextId = ctx;
        p.opnum = opnum;
        p.first = first;
        p.last = last;
        return p;
    }
    DcePdu response(uint32_t call, uint16_t ctx, bool first = true, bool last = true) {
        DcePdu p;
        p.type = dissect::kDceResponse;
        p.callId = call;
        p.contextId = ctx;
        p.first = first;
        p.last = last;
        return p;
    }

    struct Table {
        DceRpcTable t;
        bool lost = false;
        const DceNote *observe(const std::string &stream, uint32_t packet, const DcePdu &pdu, const std::string &stub = "", const std::string &server = "10.0.0.2",
                               const std::string &fallback = "", int64_t seq = -1, uint8_t index = 0) {
            return t.observe(stream, packet, seq, index, pdu, stub, server, fallback, 64u << 20, lost);
        }
    };
}

TEST(DceRpcTower, ReadsTheFloorsOfAnIpTcpTowerAndANamedPipeTower) {
    const std::string tcp = raw(kTowerTcp), np = raw(kTowerNp);
    dissect::DceTower t;
    ASSERT_TRUE(dissect::parseEpmTower(reinterpret_cast<const uint8_t *>(tcp.data()), tcp.size(), t));
    EXPECT_EQ(t.uuid, kSrvsvc);
    EXPECT_EQ(t.version, 3u) << "major 3, minor 0";
    EXPECT_EQ(t.protocol, "ncacn_ip_tcp");
    EXPECT_EQ(t.port, 49667) << "the port is big-endian: c2 03 on the wire";
    EXPECT_EQ(t.host, "10.0.0.2");
    EXPECT_FALSE(t.udp);
    dissect::DceTower p;
    ASSERT_TRUE(dissect::parseEpmTower(reinterpret_cast<const uint8_t *>(np.data()), np.size(), p));
    EXPECT_EQ(p.protocol, "ncacn_np");
    EXPECT_EQ(p.address, "\\PIPE\\srvsvc");
    EXPECT_EQ(p.port, 0);
}

TEST(DceRpcTower, RejectsTowersThatDoNotFit) {
    const std::string tcp = raw(kTowerTcp);
    dissect::DceTower t;
    for (size_t cut = 0; cut + 1 < tcp.size(); ++cut) {
        dissect::DceTower x;
        const bool ok = dissect::parseEpmTower(reinterpret_cast<const uint8_t *>(tcp.data()), cut, x);
        if (cut < 30) EXPECT_FALSE(ok) << cut;   // not even the interface floor
    }
    EXPECT_FALSE(dissect::parseEpmTower(nullptr, 0, t));
    std::string bad = tcp;
    bad[0] = 0;   // zero floors
    bad[1] = 0;
    EXPECT_FALSE(dissect::parseEpmTower(reinterpret_cast<const uint8_t *>(bad.data()), bad.size(), t));
}

TEST(DceRpcEpmAnswer, MapAndLookupAnswersAreRead) {
    const auto parse = [](uint16_t opnum, bool little, const std::string &stub, std::vector<dissect::DceTower> &out) {
        return dissect::parseEpmAnswer(opnum, little, reinterpret_cast<const uint8_t *>(stub.data()), stub.size(), out);
    };
    std::vector<dissect::DceTower> t;
    ASSERT_TRUE(parse(3, true, raw(kMapOne), t));
    ASSERT_EQ(t.size(), 1u);
    EXPECT_EQ(t[0].port, 49667);
    t.clear();
    ASSERT_TRUE(parse(3, false, raw(kMapBe), t)) << "big-endian NDR";
    ASSERT_EQ(t.size(), 1u);
    EXPECT_EQ(t[0].uuid, kSrvsvc);
    t.clear();
    ASSERT_TRUE(parse(3, true, raw(kMapTwo), t));
    ASSERT_EQ(t.size(), 2u);
    EXPECT_EQ(t[1].protocol, "ncacn_np");
    t.clear();
    ASSERT_TRUE(parse(2, true, raw(kLookup), t));
    ASSERT_EQ(t.size(), 3u);
    EXPECT_EQ(t[0].uuid, kSrvsvc);
    EXPECT_EQ(t[1].uuid, kSamr);
    EXPECT_TRUE(t[2].udp);
    EXPECT_EQ(t[2].port, 49700);
    t.clear();
    EXPECT_FALSE(parse(1, true, raw(kMapOne), t)) << "only opnum 2 and 3 are answers with towers";
}

TEST(DceRpcEpmAnswer, TruncatedAndMutatedAnswersNeverReadOutside) {
    std::mt19937 rng(0x6d70);
    for (const char *hexText: {kMapOne, kMapBe, kMapTwo, kLookup}) {
        const std::string good = raw(hexText);
        for (size_t cut = 0; cut <= good.size(); ++cut) {
            std::vector<dissect::DceTower> t;
            const std::string part = good.substr(0, cut);
            dissect::parseEpmAnswer(3, true, reinterpret_cast<const uint8_t *>(part.data()), part.size(), t);
            dissect::parseEpmAnswer(2, true, reinterpret_cast<const uint8_t *>(part.data()), part.size(), t);
            EXPECT_LE(t.size(), 2u * DceRpcTable::kMaxTowers);
        }
        for (int round = 0; round < 400; ++round) {
            std::string m = good;
            for (int k = 0; k < 1 + round % 4; ++k) m[rng() % m.size()] = static_cast<char>(rng());
            std::vector<dissect::DceTower> t;
            dissect::parseEpmAnswer(3, round % 2 == 0, reinterpret_cast<const uint8_t *>(m.data()), m.size(), t);
            dissect::parseEpmAnswer(2, round % 2 == 0, reinterpret_cast<const uint8_t *>(m.data()), m.size(), t);
        }
    }
}

TEST(DceRpcTable, AnAcceptedContextNamesTheInterfaceOfLaterRequests) {
    Table x;
    x.observe("s", 1, bind(1, {{0, kSrvsvc, 3}, {1, kSamr, 1}}));
    EXPECT_EQ(x.t.context("s", 0), nullptr) << "proposed, not yet accepted";
    x.observe("s", 2, bindAck(1, {0, 2}));
    ASSERT_NE(x.t.context("s", 0), nullptr);
    EXPECT_EQ(x.t.context("s", 0)->uuid, kSrvsvc);
    EXPECT_EQ(x.t.context("s", 1), nullptr) << "provider-rejection";
    const DceNote *r = x.observe("s", 3, request(2, 0, 15));
    EXPECT_EQ(r->iface, kSrvsvc);
    EXPECT_EQ(r->ifVersion, 3u);
    EXPECT_EQ(r->opnum, 15);
    EXPECT_EQ(r->flags & DceNote::kUnknownContext, 0);
    const DceNote *u = x.observe("s", 4, request(3, 1, 4));
    EXPECT_TRUE(u->flags & DceNote::kUnknownContext) << "context 1 was rejected";
    EXPECT_TRUE(u->iface.empty());
    const DceNote *other = x.observe("other", 5, request(4, 0, 4), "", "10.0.0.2", kSamr);
    EXPECT_EQ(other->iface, kSamr) << "assumed from the fallback";
    EXPECT_TRUE(other->flags & DceNote::kAssumed);
    EXPECT_TRUE(other->flags & DceNote::kUnknownContext);
}

TEST(DceRpcTable, AResponseLearnsTheOpnumAndPacketOfItsRequest) {
    Table x;
    x.observe("s", 1, bind(1, {{0, kSrvsvc, 3}}));
    x.observe("s", 2, bindAck(1, {0}));
    x.observe("s", 3, request(7, 0, 15));
    x.observe("s", 4, request(8, 0, 9));
    const DceNote *r8 = x.observe("s", 5, response(8, 0));
    EXPECT_TRUE(r8->flags & DceNote::kMatched);
    EXPECT_EQ(r8->opnum, 9);
    EXPECT_EQ(r8->requestPacket, 4u);
    const DceNote *r7 = x.observe("s", 6, response(7, 0));
    EXPECT_EQ(r7->opnum, 15);
    EXPECT_EQ(r7->requestPacket, 3u);
    const DceNote *none = x.observe("s", 7, response(99, 0));
    EXPECT_FALSE(none->flags & DceNote::kMatched);
    DcePdu fault = response(7, 0);
    fault.type = dissect::kDceFault;
    EXPECT_TRUE(x.observe("s", 8, fault)->flags & DceNote::kMatched);
    EXPECT_EQ(x.observe("t", 9, response(8, 0))->flags & DceNote::kMatched, 0) << "another stream";
}

TEST(DceRpcTable, FragmentsOfOneCallAreChainedAndTheEarlierOnesLearnWhereItCompleted) {
    Table x;
    x.observe("s", 1, request(5, 0, 3, true, false), "aaaa");
    x.observe("s", 2, request(5, 0, 3, false, false), "bbbbbb");
    const DceNote *last = x.observe("s", 3, request(5, 0, 3, false, true), "cc");
    ASSERT_TRUE(last->flags & DceNote::kCompletes);
    const auto *m = x.t.message(last->message);
    ASSERT_NE(m, nullptr);
    EXPECT_EQ(m->bytes, 12u);
    EXPECT_EQ(m->fragments, 3);
    EXPECT_EQ(m->packets, (std::vector<uint32_t>{1, 2, 3}));
    EXPECT_TRUE(x.t.note(1, -1, 0)->flags & DceNote::kCompletedLater);
    EXPECT_EQ(x.t.note(1, -1, 0)->completedIn, 3u);
    EXPECT_EQ(x.t.note(2, -1, 0)->completedIn, 3u);
    EXPECT_FALSE(last->flags & DceNote::kCompletedLater);
    EXPECT_EQ(x.t.noteCount(), 3u);
}

TEST(DceRpcTable, ARequestAndItsResponseAreSeparateChains) {
    Table x;
    x.observe("s", 1, request(5, 0, 3, true, false), "aaaa");
    x.observe("s", 2, response(5, 0, true, false), "rrrr");
    const DceNote *q = x.observe("s", 3, request(5, 0, 3, false, true), "bb");
    const DceNote *r = x.observe("s", 4, response(5, 0, false, true), "ss");
    EXPECT_EQ(x.t.message(q->message)->packets, (std::vector<uint32_t>{1, 3}));
    EXPECT_EQ(x.t.message(r->message)->packets, (std::vector<uint32_t>{2, 4}));
    EXPECT_EQ(x.t.message(r->message)->bytes, 6u);
}

TEST(DceRpcTable, AFragmentWithoutItsStartAndAReusedCallIdAreHandled) {
    Table x;
    const DceNote *orphan = x.observe("s", 1, request(5, 0, 3, false, true), "zz");
    EXPECT_TRUE(orphan->flags & DceNote::kMissingStart);
    EXPECT_FALSE(orphan->flags & DceNote::kCompletes);
    x.observe("s", 2, request(6, 0, 3, true, false), "aa");
    x.observe("s", 3, request(6, 0, 3, true, false), "bb");   // the call id starts over: the first chain is forgotten
    const DceNote *done = x.observe("s", 4, request(6, 0, 3, false, true), "cc");
    EXPECT_EQ(x.t.message(done->message)->packets, (std::vector<uint32_t>{3, 4}));
    EXPECT_FALSE(x.t.note(2, -1, 0)->flags & DceNote::kCompletedLater);
}

TEST(DceRpcTable, ConnectionlessFragmentsMayArriveInAnyOrderAndRepeat) {
    // fragment numbers 2 (last), 0, 1: the chain completes with the middle one
    const auto cl = [](uint32_t seq, uint32_t frag, bool last) {
        DcePdu p = request(seq, 0, 7, frag == 0, last);
        p.connectionless = true;
        p.fragment = frag;
        p.interfaceUuid = kSrvsvc;
        p.interfaceVersion = 3;
        return p;
    };
    Table x;
    x.observe("cl:act", 10, cl(4, 2, true), "33");
    x.observe("cl:act", 11, cl(4, 0, false), "1111");
    const DceNote *dup = x.observe("cl:act", 12, cl(4, 0, false), "1111");
    EXPECT_TRUE(dup->flags & DceNote::kDuplicate);
    const DceNote *done = x.observe("cl:act", 13, cl(4, 1, false), "2222");
    ASSERT_TRUE(done->flags & DceNote::kCompletes);
    EXPECT_EQ(done->iface, kSrvsvc) << "named by the header, no Bind";
    EXPECT_EQ(x.t.message(done->message)->packets, (std::vector<uint32_t>{11, 13, 10}));
    EXPECT_EQ(x.t.message(done->message)->bytes, 10u);
    EXPECT_EQ(x.t.note(10, -1, 0)->completedIn, 13u);
    EXPECT_EQ(x.t.note(11, -1, 0)->completedIn, 13u);
    EXPECT_FALSE(x.t.note(12, -1, 0)->flags & DceNote::kCompletedLater);
}

TEST(DceRpcTable, ASinglePduNeedsNoMessage) {
    Table x;
    x.observe("s", 1, request(1, 0, 3), "abc");
    EXPECT_EQ(x.t.messageCount(), 0u);
    EXPECT_FALSE(x.t.note(1, -1, 0)->flags & (DceNote::kCompletes | DceNote::kFragment));
}

TEST(DceRpcTable, TheEndpointMapperAnswerBecomesAPortMapFromThatPacketOn) {
    Table x;
    x.observe("epm", 1, bind(1, {{0, dissect::kDceEpmUuid, 3}}));
    x.observe("epm", 2, bindAck(1, {0}));
    x.observe("epm", 3, request(2, 0, 3), "ignored");
    const DceNote *a = x.observe("epm", 4, response(2, 0), raw(kMapOne), "10.0.0.2");
    ASSERT_TRUE(a->flags & DceNote::kCompletes);
    const auto *m = x.t.message(a->message);
    ASSERT_TRUE(m->epm);
    ASSERT_EQ(m->towers.size(), 1u);
    EXPECT_EQ(m->towers[0].uuid, kSrvsvc);
    const auto *e = x.t.endpoint("10.0.0.2", 49667, false, 4);
    ASSERT_NE(e, nullptr);
    EXPECT_EQ(e->uuid, kSrvsvc);
    EXPECT_EQ(e->from, 4u);
    EXPECT_EQ(x.t.endpoint("10.0.0.2", 49667, false, 3), nullptr) << "not before the answer";
    EXPECT_EQ(x.t.endpoint("10.0.0.2", 49667, true, 9), nullptr) << "TCP, not UDP";
    EXPECT_EQ(x.t.endpoint("10.0.0.3", 49667, false, 9), nullptr);
    EXPECT_EQ(x.t.endpoint("10.0.0.2", 49668, false, 9), nullptr);
}

TEST(DceRpcTable, AnAnswerInSeveralFragmentsIsReadWhole) {
    const std::string stub = raw(kMapOne);
    Table x;
    x.observe("epm", 1, bind(1, {{0, dissect::kDceEpmUuid, 3}}));
    x.observe("epm", 2, bindAck(1, {0}));
    x.observe("epm", 3, request(2, 0, 3));
    x.observe("epm", 4, response(2, 0, true, false), stub.substr(0, 50), "10.0.0.2");
    x.observe("epm", 5, response(2, 0, false, false), stub.substr(50, 40), "10.0.0.2");
    const DceNote *done = x.observe("epm", 6, response(2, 0, false, true), stub.substr(90), "10.0.0.2");
    ASSERT_TRUE(done->flags & DceNote::kCompletes);
    EXPECT_EQ(x.t.message(done->message)->bytes, stub.size());
    EXPECT_EQ(x.t.message(done->message)->towers.size(), 1u);
    EXPECT_NE(x.t.endpoint("10.0.0.2", 49667, false, 6), nullptr);
    EXPECT_EQ(x.t.endpoint("10.0.0.2", 49667, false, 5), nullptr);
}

TEST(DceRpcTable, ASealedAnswerIsNeverReadAsPlaintext) {
    Table x;
    x.observe("epm", 1, bind(1, {{0, dissect::kDceEpmUuid, 3}}));
    x.observe("epm", 2, bindAck(1, {0}));
    x.observe("epm", 3, request(2, 0, 3));
    DcePdu sealed = response(2, 0);
    sealed.encrypted = true;
    const DceNote *a = x.observe("epm", 4, sealed, raw(kMapOne), "10.0.0.2");
    EXPECT_FALSE(a->flags & DceNote::kCompletes);
    EXPECT_EQ(x.t.endpointCount(), 0u);
}

TEST(DceRpcTable, TheAnswerNeedsTheEndpointMapperAndAKnownOpnum) {
    Table x;
    x.observe("a", 1, bind(1, {{0, kSrvsvc, 3}}));
    x.observe("a", 2, bindAck(1, {0}));
    x.observe("a", 3, request(2, 0, 3));
    x.observe("a", 4, response(2, 0), raw(kMapOne));
    EXPECT_EQ(x.t.endpointCount(), 0u) << "SRVSVC opnum 3 is not ept_map";
    Table y;   // no Bind, port 135 supplies the interface
    y.observe("b", 1, request(2, 0, 3), "", "10.0.0.2", dissect::kDceEpmUuid);
    y.observe("b", 2, response(2, 0), raw(kMapOne), "10.0.0.2", dissect::kDceEpmUuid);
    EXPECT_NE(y.t.endpoint("10.0.0.2", 49667, false, 2), nullptr);
    Table z;   // the request was not captured: the opnum is unknown
    z.observe("c", 1, response(2, 0), raw(kMapOne), "10.0.0.2", dissect::kDceEpmUuid);
    EXPECT_EQ(z.t.endpointCount(), 0u);
}

TEST(DceRpcTable, ALookupAnswerListsEveryInterfaceAndMarksAPortSharedByTwoAsAmbiguous) {
    Table x;
    x.observe("epm", 1, request(2, 0, 2), "", "10.0.0.2", dissect::kDceEpmUuid);
    const DceNote *a = x.observe("epm", 2, response(2, 0), raw(kLookup), "10.0.0.2", dissect::kDceEpmUuid);
    ASSERT_TRUE(a->flags & DceNote::kCompletes);
    EXPECT_EQ(x.t.message(a->message)->towers.size(), 3u);
    const auto *tcp = x.t.endpoint("10.0.0.2", 49667, false, 2);
    ASSERT_NE(tcp, nullptr);
    EXPECT_TRUE(tcp->uuid.empty()) << "SRVSVC and SAMR both listen on 49667: the interface is not guessed";
    const auto *udp = x.t.endpoint("10.0.0.2", 49700, true, 2);
    ASSERT_NE(udp, nullptr);
    EXPECT_EQ(udp->uuid, kSrvsvc);
}

TEST(DceRpcTable, AnotherInterfaceBehindAKnownPortIsAmbiguousFromThenOn) {
    Table x;
    x.observe("epm", 1, request(2, 0, 3), "", "10.0.0.2", dissect::kDceEpmUuid);
    x.observe("epm", 2, response(2, 0), raw(kMapOne), "10.0.0.2", dissect::kDceEpmUuid);
    x.observe("epm", 3, request(3, 0, 3), "", "10.0.0.2", dissect::kDceEpmUuid);
    x.observe("epm", 4, response(3, 0), raw(kMapOne), "10.0.0.2", dissect::kDceEpmUuid);
    EXPECT_EQ(x.t.endpointCount(), 1u) << "the same interface again adds nothing";
    EXPECT_EQ(x.t.endpoint("10.0.0.2", 49667, false, 9)->uuid, kSrvsvc);
}

TEST(DceRpcTable, AskingTwiceForTheSamePduReturnsTheFirstAnswerAndChangesNothing) {
    Table x;
    const DceNote *a = x.observe("s", 1, request(5, 0, 3, true, false), "aaaa");
    const size_t memory = x.t.memory();
    const DceNote *b = x.observe("s", 1, request(5, 0, 3, true, false), "aaaa");
    EXPECT_EQ(a, b);
    EXPECT_EQ(x.t.memory(), memory);
}

TEST(DceRpcTable, ThePduIndexAndStreamSequenceKeepNotesApart) {
    Table x;
    x.observe("s", 1, request(1, 0, 3), "", "10.0.0.2", "", 100, 0);
    x.observe("s", 1, request(2, 0, 4), "", "10.0.0.2", "", 100, 1);
    x.observe("s", 1, request(3, 0, 5), "", "10.0.0.2", "", 700, 0);
    EXPECT_EQ(x.t.note(1, 100, 0)->opnum, 3);
    EXPECT_EQ(x.t.note(1, 100, 1)->opnum, 4);
    EXPECT_EQ(x.t.note(1, 700, 0)->opnum, 5);
    EXPECT_EQ(x.t.note(1, -1, 0), nullptr);
}

TEST(DceRpcTable, TheBudgetRunsOutAndTheTableSaysSo) {
    DceRpcTable t;
    bool lost = false;
    const DcePdu p = request(1, 0, 3, true, false);
    EXPECT_NE(t.observe("s", 1, -1, 0, p, "x", "", "", 1u << 20, lost), nullptr);
    EXPECT_FALSE(lost);
    DceRpcTable small;
    EXPECT_EQ(small.observe("s", 1, -1, 0, p, "x", "", "", 200, lost), nullptr);
    EXPECT_TRUE(lost);
    lost = false;
    DceRpcTable tiny;   // room for the note of a chain but not for another fragment
    size_t used = 0;
    for (uint32_t i = 1; i < 2000 && !lost; ++i) {
        tiny.observe("s", i, -1, 0, request(i, 0, 3, true, false), std::string(100, 'x'), "", "", 20000, lost);
        used = tiny.memory();
    }
    EXPECT_TRUE(lost);
    EXPECT_LE(used, 20000u);
}

TEST(DceRpcTable, AClearedTableForgetsEverything) {
    Table x;
    x.observe("epm", 1, request(2, 0, 3), "", "10.0.0.2", dissect::kDceEpmUuid);
    x.observe("epm", 2, response(2, 0), raw(kMapOne), "10.0.0.2", dissect::kDceEpmUuid);
    ASSERT_GT(x.t.memory(), 0u);
    x.t.clear();
    EXPECT_EQ(x.t.memory(), 0u);
    EXPECT_EQ(x.t.noteCount(), 0u);
    EXPECT_EQ(x.t.endpointCount(), 0u);
}
